# Generated by Django 5.0.7 on 2024-07-29 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sm', '0002_alter_teacher_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='code',
            field=models.IntegerField(unique=True),
        ),
    ]
